P10/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include("myapp.urls")),
    path('base/',views.base,name="Base"),
    path('',views.home,name="Home"),

]

myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('index/',views.index,name="Index"),
    path('profile/',views.profile,name="Profile"),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("<h1>Project is on AIR</h1>")

def base(request):
    return render(request,"_base.html")

def home(request):
    return render(request,"myapp/_home.html")

def profile(request):
    name="Pyspiders"
    return render(request,"myapp/_profile.html",{'name':name})

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
      <title>Base Html</title>
    {% endblock  %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  
</head>
<body>
  {% include "partials/_topbar.html" %}
  {% include "partials/_navbar.html" %}
  {% block content %}
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome to Base Page</h1>
      </div>
    </div>
  {% endblock  %}
  {% include "partials/_footer.html" %}
</body>
</html>

templates/myapp/_home.html
{% extends "_base.html" %}

{% block title %}
  <title>Home Html</title>
{% endblock  %}

{% block content %}
  <div class="container">
      <div class="jumbotron">
          <h1>Welcome to Home Page</h1>
      </div>
  </div>
{% endblock  %}

templates/myapp/_profile.html
{% extends "_base.html" %}

{% block title %}
  <title>Profile Html</title>
{% endblock  %}

{% block content %}
  <div class="container">
      <div class="jumbotron">
          <h1>Welcome to {{name}} profile page</h1>
      </div>
  </div>
{% endblock  %}

templates/partials/_footer.html
<!--Footer Html page-->
<div class="alert alert-info" role="alert">
    <center>Footer</center>
</div>

templates/partials/_navbar.html
<!--Nav bar Html page-->
<div class="container">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'Home' %}" >Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:Profile' %}">Profile</a>
        </li>
    </ul>
</div>

templates/partials/_topbar.html
<!--Top bar html page-->
<div class="alert alert-primary" role="alert">
    <center>Top bar</center>
</div>